### ISSUE TITLE
Something wrong happen trying to export one file

### ISSUE THREAD

**Issue by MrElectroNick** [jabiertxof/gimpToSVG#6]
PSD file -> GIMP -> Keep 2-3 visible layers -> Export

I'm not sure I'm doing it correctly but in any case screenshot and stack trace can be helpful:

Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 699, in response
    dialog.res = run_script(params)
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "/usr/lib/gimp/2.0/plug-ins/gimp_export_as_svg.py", line 195, in export_as_svg
    svg_procesed = layer_process(img, layers, only_visible, dupe, dest, flatten, remove_offsets, crop, inkscape_layers, text_layers, resolution_96, False, urlencode_files, strip_extension, embed_images)
  File "/usr/lib/gimp/2.0/plug-ins/gimp_export_as_svg.py", line 151, in layer_process
    data += layer_process(layer.children, only_visible, dupe, path, flatten, remove_offsets, crop, inkscape_layers)
  File "/usr/lib/gimp/2.0/plug-ins/gimp_export_as_svg.py", line 47, in layer_process
    get_resolution = pdb.gimp_image_get_resolution(dupe)
TypeError: wrong parameter type
![screenshot from 2016-11-18 16 25 21](https://cloud.githubusercontent.com/assets/3267843/20433321/b3278c20-adab-11e6-8aa0-b626b960a926.png)

**Comment by doubtintom** [comment]
Similar here, but the error is threading through different lines of **gimpfu.py**  but same lines of **gimp_export_as_svg.py**, see below:

Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line **736**, in response
    dialog.res = run_script(params)
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line **361**, in run_script
    return apply(function, params)
  File "/usr/lib/gimp/2.0/plug-ins/gimp_export_as_svg.py", line **195**, in export_as_svg
    svg_procesed = layer_process(img, layers, only_visible, dupe, dest, flatten, remove_offsets, crop, inkscape_layers, text_layers, resolution_96, False, urlencode_files, strip_extension, embed_images)
  File "/usr/lib/gimp/2.0/plug-ins/gimp_export_as_svg.py", line **151**, in layer_process
    data += layer_process(layer.children, only_visible, dupe, path, flatten, remove_offsets, crop, inkscape_layers)
  File "/usr/lib/gimp/2.0/plug-ins/gimp_export_as_svg.py", line **47**, in layer_process
    get_resolution = pdb.gimp_image_get_resolution(dupe)

GIMP 2.8.16
Linux Mint 18
64 bit
python 2.7.12 

Say, what python version should be used, 2 or 3?

Tom

**Comment by jabiertxof** [comment]
Fixed in r.3d705c7.
Thanks for fill the bug!
